config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions, only: [:new]
  post '/charges', controller: :subscriptions, action: :create

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks}

  root controller: :articles, action: :index

  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :update]
  end

  namespace :publishing do
    resources :articles, only: [:create, :new, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title , use: :slugged

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  belongs_to :author, class_name: 'User'


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates_presence_of :content
  validates_email_format_of :email,
                            message: 'Email is invalid',
                            allow_blank: true

  before_validation on: :create do |resource|
    resource.send(:initialize_state_machines, dynamic: :force)
  end

  default_scope -> { with_state(:approved) }
  scope :not_rejected, -> { unscoped.where.not(state: :rejected)}

  state_machine :state, initial: :submitted do
    event :approve do
      transition submitted: :approved
    end

    event :reject do
      transition submitted: :rejected
    end
  end
end

app/models/news_agency.rb
class NewsAgency < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode


  def full_address
    Geocoder.address([self.street_address,
                      self.post_code,
                      self.city].join(','))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates_presence_of :name

  has_many :articles


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def can?(action, object)
    begin
      policy_method = "#{action.to_s}?"
      Pundit.policy!(self, object).send(policy_method)
    rescue NoMethodError => e
      policy_name = "#{object.class.name.to_s}Policy"
      logger.debug "Undefined Pundit policy method: #{policy_name}##{policy_method}, returned false by default"
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_agency
  before_action :configure_permitted_parameters, if: :devise_controller?


  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(error)
    if error.policy.class.to_s.underscore == 'article_policy'
      message = 'You need to purchase a subscription'
    else
      message = 'You are not authorized to perform this action.'
    end
    redirect_to root_path, notice: message
    #redirect_back(fallback_location: root_path, notice: message)
  end

  def get_agency
    @agency = NewsAgency.first
  end


  def configure_permitted_parameters
    permitted_parameters = devise_parameter_sanitizer.instance_values['permitted']
    attributes = [:name]
    attributes.each do |attribute|
      permitted_parameters[:sign_up] << attribute
      permitted_parameters[:account_update] << attribute
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only: :show

  def index
    @articles = Article.all
  end

  def show
  end


  private

  def get_article
    @article = Article.friendly.find(params[:id])
    authorize @article
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_article, only: [:create]

  def create
    comment = Comment.create(comment_params.merge!(article: @article))
    if comment.persisted?
      flash[:success] = 'Your comment was added successfully and will be reviews before publication'
    else
      message = ''
      comment.errors.full_messages.each do |error_message|
        message += error_message
      end
      flash[:success] = message + '<br>'
    end
    redirect_to article_path(@article)
  end

  def update
    comment = Comment.not_rejected.find params[:id]
    if params[:transition]
      comment.send(params[:transition].to_sym)
    end
    redirect_to article_path(comment.article), notice: "Comment was #{comment.state}!"
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :email)
  end

  def get_article
    @article = Article.friendly.find(params[:article_id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path, notice: 'That did not work!'
  end
end

app/controllers/publishing/articles_controller.rb
class Publishing::ArticlesController < Publishing::PublishingController

  def index

  end

  def create
    article = Article.create(article_params.merge!(author: current_user))
    if article.persisted?
      redirect_to publishing_articles_path, notice: 'Your article has been submitted for review.'
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit!
  end
end

app/controllers/publishing/publishing_controller.rb
class Publishing::PublishingController < ApplicationController
  layout 'publishing'
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :check_env
  def new

  end

  def create
    customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: stripe_token(params)
    )

    charge = Stripe::Charge.create(
        customer: customer.id,
        amount: 1000,
        description: 'Subscription to News Service',
        currency: 'sek'
    )
    if charge.paid?
      current_user.update_attribute(:subscriber, true)
      message = 'Welcome as a subscriber'
    else
      message = 'Your payment did not clear. Subscription could not be purchased!'
    end
    redirect_to root_path, notice: message
  end



  private
  def stripe_token(params)
    Rails.env.test? ? generate_test_token : params[:stripeToken]
  end

  def generate_test_token
    StripeMock.generate_card_token
  end

  def check_env
    StripeMock.start if Rails.env.test?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



  def get_comments(article)
    if current_user.owner?
      article.comments.not_rejected
    else
      article.comments
    end
  end
end

app/views/articles/index.html.haml
- @articles.each do |article|
  %div{ id: "#{dom_id(article)}" }
    %h2= link_to article.title, article_path(article)
    %p= truncate(article.content, length: 150) { link_to ' (continued)', article_path(article)}

app/views/articles/show.html.haml
%article
  %h2= @article.title.html_safe
  %p= @article.content.html_safe

= form_with url: article_comments_path(@article), scope: :comment do |form|
  %p= form.label :email
  = form.text_field :email, id: 'comment_email'
  %p= form.label :content, 'Comment'
  = form.text_area :content, cols: 50, rows: 5, id: 'comment_content'
  = form.submit 'Create Comment'

- if get_comments(@article).any?
  - get_comments(@article).each do |comment|
    %p= "Commented by: #{comment.email.empty? ? 'anonymous' : comment.email}"
    %p= comment.content
    - if current_user.can?(:moderate, comment)
      = link_to 'Approve', article_comment_path(@article, comment, transition: :approve), method: :put if comment.submitted?
      = link_to 'Reject', article_comment_path(@article, comment, transition: :reject), method: :put if comment.submitted?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', http: {equiv: 'Content-Type'}}/
    %title RailsDemo
    = csrf_meta_tags
    %link{href: 'https://fonts.googleapis.com/css?family=UnifrakturMaguntia', rel: 'stylesheet'}/
    = stylesheet_link_tag 'application', media: 'all', data: {turbolinks: {track: 'reload'}}
    = javascript_include_tag 'application', data: {turbolinks: {track: 'reload'}}
    %script{src: 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBPpYLyqAKFmeBtAJvRUhcukDr0qZ8lyUc', data: {turbolinks: {track: 'reload'}}}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js'}


  %body
    .container
      %header
        .details
          %span
            - if user_signed_in?
              Signed in as: #{link_to current_user.name, edit_registration_path(current_user)}
              |
              - unless current_user.subscriber?
                = link_to 'Subscribe', new_subscription_path
                |
              = link_to 'Sign out', destroy_user_session_path, method: :delete
              |
            - else
              = link_to('Create an account', new_user_registration_path)
              |
              = link_to('Login', new_user_session_path)
              |
              =link_to('Login with Facebook', user_facebook_omniauth_authorize_path)
              |
        %h1
          = link_to 'Ruby Observer', root_path
        .details
          %span
            The news service that doesn't make sense
            |
            = Date.today.to_s(:long)
        - flash.each do |key, value|
          .flash
            %span
              %strong= value.html_safe
      %div{style: 'min-height: 400px'}
        = yield
      %footer
        A
        %a{href: '#'} Craft Academy
        Publication
        #map{style: 'height: 200px; width: 100%'}
        %p
          %small= [@agency.street_address, @agency.post_code, @agency.city].join(', ') if @agency

  :javascript
    $(document).on("turbolinks:load", function () {
      var map = new GMaps({
          el: "#map",
          lat: #{@agency.latitude},
          lng: #{@agency.longitude},
          zoom: 11,
          zoomControl : true,
          zoomControlOpt: {
              style : "SMALL",
              position: "TOP_LEFT"
          },
          panControl : true,
          streetViewControl : false,
          mapTypeControl: false,
          overviewMapControl: false
      });
      map.addMarker({
          lat: map.getCenter().lat(),
          lng: map.getCenter().lng(),
      });
      map.addStyle({
          styledMapName:"Styled Map",
          styles: styles,
          mapTypeId: "map_style"
      });
      map.setStyle("map_style");
    });

app/views/layouts/publishing.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', http: {equiv: 'Content-Type'}}/
    %title RailsDemo
    = csrf_meta_tags
    %link{href: 'https://fonts.googleapis.com/css?family=UnifrakturMaguntia', rel: 'stylesheet'}/
    = stylesheet_link_tag 'application', media: 'all', data: {turbolinks: {track: 'reload'}}
    = javascript_include_tag 'application', data: {turbolinks: {track: 'reload'}}
    %script{src: 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBPpYLyqAKFmeBtAJvRUhcukDr0qZ8lyUc', data: {turbolinks: {track: 'reload'}}}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js'}


  %body
    .container
      %header
        .details
          %span
            - if user_signed_in?
              Signed in as: #{link_to current_user.name, edit_registration_path(current_user)}
              |
              - unless current_user.subscriber?
                = link_to 'Subscribe', new_subscription_path
                |
              = link_to 'Sign out', destroy_user_session_path, method: :delete
              |
            - else
              = link_to('Create an account', new_user_registration_path)
              |
              = link_to('Login', new_user_session_path)
              |
              =link_to('Login with Facebook', user_facebook_omniauth_authorize_path)
              |
        %h1 Publishing Land
        - flash.each do |key, value|
          .flash
            %span
              %strong= value.html_safe
      %div{style: 'min-height: 400px'}
        = yield
      %footer
        A
        %a{href: '#'} Craft Academy
        Publication

app/views/publishing/articles/create.html.haml
%h1 Publishing::Articles#create
%p Find me in app/views/publishing/articles/create.html.haml

app/views/publishing/articles/index.html.haml
= link_to 'Create Article', new_publishing_article_path

app/views/publishing/articles/new.html.haml
= form_with url: publishing_articles_path, scope: :article do |form|
  %p= form.label :title
  = form.text_area :title, id: 'article_title', class: 'editable-header'
  %p= form.label :content
  = form.text_area :content, cols: 50, rows: 5, id: 'article_content', class: 'content'
  = form.submit 'Submit for review'

:javascript
  var editor = new MediumEditor('.content', {
    toolbar: {
        buttons: ['bold', 'italic', 'quote', 'pre', 'h1', 'h2', 'h3', 'unorderedlist'],
        diffLeft: 25,
        diffTop: 10,
    },
    placeholder: {
        /* This example includes the default options for placeholder,
           if nothing is passed this is what it used */
        text: 'Add content here...',
        hideOnClick: true
    },
    anchor: {
        /* These are the default options for anchor form,
           if nothing is passed this is what it used */
        customClassOption: null,
        customClassOptionText: 'Button',
        linkValidation: false,
        placeholderText: 'Paste or type a link',
        targetCheckbox: true,
        targetCheckboxText: 'Open in new window'
    },
    paste: {
        cleanPastedHTML: true,
        cleanAttrs: ['style', 'dir'],
        cleanTags: ['label', 'meta'],
        unwrapTags: ['sub', 'sup']
    },
    autoLink: true,
    imageDragging: true
  });

  var headerEditor = new MediumEditor('.editable-header', {
    toolbar: false,
    style: {
    prop: 'font-weight', value: '700|bold'}
  });

app/views/subscriptions/new.html.haml
%h2 Subscription page

%p How nice that you want to become a paying reader

= form_tag charges_path do
  %script.stripe-button{ src: 'https://checkout.stripe.com/checkout.js',
      data: {amount: 1000,
      description: 'Subscription to Ruby Observer',
      key: "#{ENV['STRIPE_APP']}",
      currency: 'sek',
      email: "#{current_user.email if current_user}"}}
  %button{type: 'submit'} Pay with Card